apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vm2cloud-demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vm2cloud-demo
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
